### ISSUE TITLE
Looks interesting.

### ISSUE THREAD

**Issue by Rainer-Lang** [robertoestivill/intentbuilder#1]
Do you have further plans?

**Comment by robertoestivill** [comment]
Nothing written in stone to be honest. Also the intent management is pretty much covered.
The only thing i was thinking on, was to extend the functionality a little bit to allow the intent to be launched within the same method chain. Something like the following

``` java

// with explicit context
new IntentLauncher()
    .context(mContext)
    .activity(MyActivity.class)
    .extra("one_extra", "one_value")
    .extra("two_extra", 123)
    .launch() // might run build() inside?
```

`context()` is only useful and should only be called when a call `activity()`, `broadcast()` or `service()` happens immediately after. This means that we know exactly how the intent will be resolve, therefore we could launch it using the passed in context.
Need to be careful though, as the passed in context might not be the same you want to launch the intent with.

If the intent is implicit, and relies on Android to be resolved (no context passed in, or class), then I was thinking about having something like the following:

``` java
// without context
new IntentLauncher()
    .action("my_cool_action")
    .extra("one_extra", "one_value")
    .extra("two_extra", 123)
    .launchService(mContext) // maybe run build() inside?
```

Where `launchService(context)` means the type of method to be invoked from the `context` argument. Similarly, we should have `launchBroadcast(context)` and `launchActivity(context)`.

Other option will be to use `activity`, `broadcast` and `service` methods to actually launch the intent, but that will require breaking changes on the API since those methods currently set the explicit class of the component into the builder.

Have any idea in mind?

**Comment by Udinic** [comment]
While you're in the "intents domain", consider adding a builder for the IntentFilter class. 

Currently, if you want to add more than one action for your broadcast receiver to listen to, you need to create a local variable for the intent filter, and cannot use the default constructor. It can be pretty annoying. Example:

``` java
// one action
registerReceiver(receiver, new IntentFilter("ACTION_BLABLA"));

// two actions
IntentFilter intentFilter = new IntentFilter("ACTION_ONE");
intentFilter.addAction("ACTION_TWO");
registerReceiver(receiver, intentFilter);

// Would be great to have something like:
registerReceiver(receiver, new IntentFilterBuilder().addAction("ACTION_ONE").addAction("ACTION_TWO").build());
```

**Comment by robertoestivill** [comment]
Thanks for your suggestion @Udinic !!
Sounds like a good feature to have at some point, however it wouldn't fit into the library name (maybe a rename for next version?)
I have just created https://github.com/robertoestivill/intentbuilder/issues/3 to track that feature and keep this conversation a general discussion about the library.
Thanks again!
